site_name: Vinlab

nav:
    - "Home": index.md
    - "About": about.md
    - "Getting started": getting-started.md
    - "User guide":
      - "Projects": ./user-guide/project.md
      - "Labels": ./user-guide/label.md
      - "Annotator": ./user-guide/annotator.md
      - "Label Data": ./user-guide/label-data.md
    - "Developer Guide": developer-guide.md
theme:
  name: material
